hm_control_cfg_dtu_ser = 99978563001
hm_control_cfg_inverter_ser = 116180215597
hm_control_cfg_channel = 23 # [3,23,40,61,75]
hm_control_cfg_pa_level = -18 # [-18,-12,-6,0]
hm_control_cfg_inverter_power_min = 30 # power that should be generated at minimum
hm_control_cfg_inverter_power_max = 300 # power that should be generated at maximum
hm_control_cfg_inverter_power_multiplier = 1 # e.g. set to "2", if a set power limit of 50 W results in 100 W generation
hm_control_cfg_inverter_power_offset = 0 # set to > 0 if you want to generate more power than needed; set to < 0 to generate less power than needed
hm_control_cfg_power_threshold = 5 # the absolute value which needs to be exceeded before setting a new power limit
hm_control_cfg_shelly3em = '192.168.1.2' # host name or ip address of Shelly 3EM
hm_control_cfg_interval = 5 # delay after power adjustment
